spring:
  profiles:
    active: local
  application:
    name: subSave
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB

mybatis:
  mapper-locations: classpath:/mapper/**/*.xml
  configuration:
    map-underscore-to-camel-case: true

jwt:
  secret-key: ${JWT_SECRET_KEY}
  access-token-expiration-millis: 3600000

management:
  endpoints:
    web:
      base-path: /actuator
      exposure:
        include: health, info

oauth:
  kakao:
    client-id: ${KAKAO_CLIENT_ID}
    redirect-uri: http://localhost:3000/auth/kakao/callback
    token-uri: https://kauth.kakao.com/oauth/token
    user-info-uri: https://kapi.kakao.com/v2/user/me
    secret: ${KAKAO_CLIENT_SECRET}

  naver:
    client-id: ${NAVER_CLIENT_ID}
    redirect-uri: http://localhost:3000/auth/naver/callback
    token-uri: https://nid.naver.com/oauth2.0/token
    user-info-uri: https://openapi.naver.com/v1/nid/me
    client-secret: ${NAVER_CLIENT_SECRET}

